[package]
name = "cl-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
class_group.workspace = true
curv-kzen.workspace = true
secp256k1.workspace = true
sha2.workspace = true
rand.workspace = true
serde.workspace = true
anyhow.workspace = true
thiserror.workspace = true
